### ISSUE TITLE
Use rustix' use-libc-auxv feature?

### ISSUE THREAD

**Issue by sophie-h** [smol-rs/async-io#179]
I ran into the problem that rustix panics when using async-io inside a 32-bit Linux sandbox with no `/proc` available. [Turns out](https://github.com/bytecodealliance/rustix/issues/977) that the default feature `use-libc-auxv` of rustix would avoid that. Is the feature intentionally disabled?

**Comment by sunfishcode** [comment]
For background, the reason this affects 32-bit x86 specifically that on 32-bit x86, the ISA syscall instructions differ between Intel and AMD (`sysenter` vs `syscall`), so on 32-bit x86 the recommended way to do syscalls is to always use the vDSO, which automatically picks the right one. Finding the vDSO requires the `AT_SYSINFO` or `AT_SYSINFO_EHDR` auxv entries.

**Comment by notgull** [comment]
The feature is intentionally disabled to avoid pulling in `libc`.

**Comment by notgull** [comment]
To clarify, my impression is that the `use-libc-auxv` feature is supposed to be enabled in downstream crates. Since there are multiple ways of getting the auxiliary vector. So I disable that feature in order to give downstream crates the freedom to choose their `auxv` implementation.

**Comment by taiki-e** [comment]
I don't think [the latest use-libc-auxv depended on libc crate](https://github.com/bytecodealliance/rustix/blob/c4ac6b6f33f2fba08de6ab92285ce5820c7fbb7d/Cargo.toml#L214), so why is it still an optional feature in the first place?

Also, looking at [the implementation](https://github.com/bytecodealliance/rustix/blob/c4ac6b6f33f2fba08de6ab92285ce5820c7fbb7d/src/backend/linux_raw/param/libc_auxv.rs):

- Enabling use-libc-auxv feature won't work with musl (with static linking, which is default) since nether weak linkage nor dlsym do not work with static linking, right?
- And to use it on musl the user will also have to enable the unstable runtime feature, right?

(See also [my previous investigation on the availability of getauxval](https://github.com/taiki-e/portable-atomic/blob/0ee58311e1094fa9eda27d80b613de61d6d811cb/src/imp/atomic128/detect/auxv.rs#L11-L32).)

I'm not opposed to enabling use-libc-auxv feature, but at this point, I guess the most reliable way is to use the rustix's libc backend on x86_32.

**Comment by notgull** [comment]
Thanks for the insight @taiki-e!

> I don't think [the latest use-libc-auxv depended on libc crate](https://github.com/bytecodealliance/rustix/blob/c4ac6b6f33f2fba08de6ab92285ce5820c7fbb7d/Cargo.toml#L214), so why is it still an optional feature in the first place?

I think it's because `/proc` can be read from in most cases. It also avoids linking to `libc` at all, at least from a `rustix` perspective. The issue above only happens when the process is sandboxed. In this case the application should be built with the `use-libc-auxv` feature enabled.

**Comment by notgull** [comment]
My opinion is that feature shouldn't be enabled, as we don't explicitly need it and we don't want to force it on users.

Unless @smol-rs/admins has a better reason why we should include this feature I'm leaning towards "don't".

**Comment by zeenix** [comment]
> My opinion is that feature shouldn't be enabled, as we don't explicitly need it and we don't want to force it on users.

I'd share this opinion but OTOH async-io panicking the application w/o any indication of why, is also something we should avoid IMO. Perhaps we can add a proxy feature, which `Async::connect` can check for and if it's not enabled, target is 32-bit x86 and there is no `/proc` available, we through our own panic (or error) that informs the call of what is happening?

**Comment by notgull** [comment]
> Perhaps we can add a proxy feature, which `Async::connect` can check for and if it's not enabled, target is 32-bit x86 and there is no `/proc` available, we throw our own panic (or error) that informs the call of what is happening?

Sounds like a good idea, but I think it belongs more in `rustix` than in `async-io`

**Comment by zeenix** [comment]
> > Perhaps we can add a proxy feature, which `Async::connect` can check for and if it's not enabled, target is 32-bit x86 and there is no `/proc` available, we throw our own panic (or error) that informs the call of what is happening?
> 
> Sounds like a good idea,

Glad you think so.

> but I think it belongs more in `rustix` than in `async-io`

The users of `async-io` shouldn't need to even know that `rustix` is involved, let alone having to add it as a dep to enable some feature. That's why I wrote that we should provide a proxy feature.

**Comment by notgull** [comment]
My idea was to add an `auxv_available` method to `rustix` that can check whether or not the auxv setup is available. Then, we can call it in our code to make sure we can use these system calls.

@sunfishcode Would you accept this PR?

**Comment by sunfishcode** [comment]
On 32-bit x86, *all* rustix APIs use the vsyscall mechanism, so they all need the auxv setup. Perhaps I'm misunderstanding, but it doesn't seem very practical to guard everything with `auxv_available`.

What about this: What if rustix fell back to using `int 0x80` instead of the vsyscall mechanism if it can't get the auxv entries, instead of panicking? The downside is that it's relatively slow. However, users would only get the slow implementation if they're using Linux < 6.4, /proc is not mounted, and they haven't enabled use-libc-auxv. I've now submitted https://github.com/bytecodealliance/rustix/pull/979 implementing this.

**Comment by notgull** [comment]
This is now fixed on the `rustix` side
